---

- name: create_waf_policy
  hosts: all
  connection: local

  tasks:
    - name: Create a pool
      bigip_asm_policy:
        server: 34.67.4.172
        user: admin
        password: Mar5827532**
        server_port: 8443
        validate_certs: no
        name: asm_policy_2
        file: /var/lib/jenkins/workspace/djarum_lab/waf_policy/f5-wafpolicy.xml
        active: yes
      delegate_to: localhost